### ISSUE TITLE
Optimization tip for react-router

### ISSUE THREAD

**Issue by iamakulov** [GoogleChromeLabs/webpack-libs-optimizations#2]
In #1, we’re working on mentioning `babel-plugin-transform-imports` which can replace a full library import with imports of specific library parts.

Turns out, this optimization is also applicable to `react-router` v3: https://github.com/ReactTraining/react-router/blob/v3/docs/guides/MinimizingBundleSize.md. We need to:

* Wait until #1 is merged
* Check if the plugin is still helpful for react-router 4
* Add a new section for `react-router` describing this optimization

Contributions are welcome :–)

**Comment by kurtextrem** [comment]
This optimization is indeed possible for a lot of libs that split components into their own files (which should be common in React env).
For example not only `react-bootstrap`, but `reactstrap` too.

**Comment by kurtextrem** [comment]
While looking at the source, it seems like this optimization should still apply to v4. So I've went ahead and added it in #1 :)

**Comment by iamakulov** [comment]
> While looking at the source, it seems like this optimization should still apply to v4. So I've went ahead and added it in #1 :)

Awesome, thanks!

**Comment by iamakulov** [comment]
Closed in #1.
