### ISSUE TITLE
Should we mention Inferno/Nervjs?

### ISSUE THREAD

**Issue by kurtextrem** [GoogleChromeLabs/webpack-libs-optimizations#8]
While Preact and Inferno have a slightly more complicated migration from React (because of incompatibilities, you have to install additional libraries for the transition groups etc), Nervjs does not.
Also, Inferno is much faster than Preact, while being also larger. But migration is even harder in my experience.

NervJS migration is painless and it seems to be overall faster than React and Preact and in some cases faster than Inferno.
See here for more details: https://github.com/NervJS/nerv/issues/10

**Comment by kurtextrem** [comment]
> Want to make a PR? :–)

Yup, I'll do it soon :)

**Comment by kurtextrem** [comment]
Sorry for taking so long!

**Comment by iamakulov** [comment]
No problem :–)
